name: Build Img2tim with CMake on Windows

on:
  push:
    branches: ["main", test/build]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release
  C_COMPILER: gcc
  ARTIFACT: windows.tar.xz

jobs:
  build:
    runs-on: "windows-latest"

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}" >> "$GITHUB_OUTPUT"

      - name: Download Ninja
        id: dl-ninja
        shell: bash
        run: choco install pkgconfiglite ninja

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_C_COMPILER=${{ env.C_COMPILER }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -G Ninja
          -S ${{ github.workspace }}

      - name: Build
        id: build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ env.BUILD_TYPE }}

      - name: Install Strip
        run: |
          cmake --install ${{ steps.strings.outputs.build-output-dir }} --prefix instdir --strip;
          cmake -E copy ${{ steps.strings.outputs.build-output-dir }}\vendor\freeimage\FreeImage.dll instdir

      - name: Pack
        working-directory: instdir\bin
        run: cmake -E tar cJfv ..\..\${{ env.ARTIFACT }} .\img2tim.exe .\FreeImage.dll

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.ARTIFACT }}
          name: ${{ env.ARTIFACT }}
